services:
  - type: web
    name: myportfolio
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn personal_profile.wsgi
    autoDeploy: true
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: personal_profile.settings
